// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDN8HGVIIWQau7XwKQDyB4-y0zKr1U7-VM',
    appId: '1:757839934271:web:b1dc7f7f283fbc7dc5598a',
    messagingSenderId: '757839934271',
    projectId: 'flutter-chat-app-d1fb8',
    authDomain: 'flutter-chat-app-d1fb8.firebaseapp.com',
    storageBucket: 'flutter-chat-app-d1fb8.firebasestorage.app',
    measurementId: 'G-FLPNH1G6SM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUP0IUaMBdt5_lsvJHHiwOMJFJ6xdi8S4',
    appId: '1:757839934271:android:aa5222d3d87d096fc5598a',
    messagingSenderId: '757839934271',
    projectId: 'flutter-chat-app-d1fb8',
    storageBucket: 'flutter-chat-app-d1fb8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXhmcpurZD1SiMCGKbT_lNBdHfbHSYUvM',
    appId: '1:757839934271:ios:18711c5533c9daa8c5598a',
    messagingSenderId: '757839934271',
    projectId: 'flutter-chat-app-d1fb8',
    storageBucket: 'flutter-chat-app-d1fb8.firebasestorage.app',
    iosBundleId: 'com.samyhesham.chatApp',
  );

}